if(NOT DEFINED RUNTIME OR NOT DEFINED WORK)
  message(FATAL_ERROR "RUNTIME and WORK required")
endif()
set(EVIDENCE "C:/Fate Soldiers 3/artifacts/phase7_precomputed_evidence.json")
foreach(RUN a b)
  execute_process(COMMAND "${RUNTIME}" --evidence "${EVIDENCE}" --root C:/DW3 --game dw3 --rid 2 --child 0 --profile length16 --mode decode --output-dir "${WORK}/${RUN}" RESULT_VARIABLE RESULT)
  if(NOT RESULT EQUAL 0)
    message(FATAL_ERROR "CLI failed")
  endif()
endforeach()
foreach(FILE phase8_runtime_manifest.json payload.rgba payload.alpha)
  file(SHA256 "${WORK}/a/${FILE}" A)
  file(SHA256 "${WORK}/b/${FILE}" B)
  if(NOT A STREQUAL B)
    message(FATAL_ERROR "Non-deterministic ${FILE}")
  endif()
endforeach()
file(WRITE "${WORK}/bad.json" "{\"dw3_descriptor_count\":2123,\"dw3_descriptor_count\":2123}")
execute_process(COMMAND "${RUNTIME}" --evidence "${WORK}/bad.json" --root C:/DW3 --game dw3 --rid 0 --mode inspect --output-dir "${WORK}/bad-output" RESULT_VARIABLE RESULT)
if(RESULT EQUAL 0)
  message(FATAL_ERROR "Accepted duplicate JSON keys")
endif()
file(WRITE "${WORK}/truncated.json" "{\"dw3_descriptor_count\":")
execute_process(COMMAND "${RUNTIME}" --evidence "${WORK}/truncated.json" --root C:/DW3 --game dw3 --rid 0 --mode inspect --output-dir "${WORK}/bad-output" RESULT_VARIABLE RESULT)
if(RESULT EQUAL 0)
  message(FATAL_ERROR "Accepted truncated JSON")
endif()
