[general]
input = "D:/Juegos/Playstation/Playstation 2/Musou/DW3_native_spike/original/SLUS_202.77"
output = "D:/Juegos/Playstation/Playstation 2/Musou/DW3_native_spike/generated/level2o_expV_recomp"
