"""Local, bounded review queue for the GitHub Copilot desktop automation.

Only named code excerpts leave the master workspace. Replies are untrusted
advice, checked against immutable requests and current source hashes. Nothing
here invokes a model, applies a patch, executes reply text or changes budgets.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
DEFAULT = ROOT / 'artifacts/copilot_bridge'
MAX_JSON = 512 * 1024

TASKS = {
    'rpc-continuation-review': {
        'objective': 'Review these current IOP guest continuation and RPC ownership excerpts. Give at most one concrete defect or explicitly bounded uncertainty with a discriminating test. Consider caller identity, suspended state, consumption once and transport retry. Use only the excerpts; do not execute code or claim original game parity. Return only the supplied JSON schema, under512 output tokens.',
        'sections': [('tools/PS2Recomp/ps2xIOP/src/emulator/core/iop_kernel.cpp', 39, 97),
                     ('tools/PS2Recomp/ps2xIOP/src/emulator/services/iop_rpc.cpp', 131, 162),
                     ('tools/PS2Recomp/ps2xIOP/src/emulator/services/iop_rpc.cpp', 273, 332)],
    },
    'modload-contract-review': {
        'objective': 'Audit the MODLOAD1.6 boot-device HLE and its tests for signed-byte, unsigned-wrap, pointer-boundary and false-equivalence risks. Read only these excerpts. Identify at most four concrete defects or explicitly bounded uncertainties, with source lines and discriminating tests. Do not run code, browse, open files, request credentials or claim original-game parity. Reply using the supplied strict JSON schema only.',
        'sections': [('tools/PS2Recomp/ps2xIOP/src/emulator/imports/iop_modload.cpp', 1, 90),
                     ('tools/PS2Recomp/ps2xIOP/tests/iop_modload_tests.cpp', 1, 170)],
    },
    'missing-import-review': {
        'objective': 'Audit the IOP missing-import barrier for incorrect continuation, nested CPU/thread ownership, unwinding and false RPC completion. Read only these excerpts and identify at most four concrete defects or bounded uncertainties. Include precise source lines and behavioral regression tests. No source edits, code execution, external research, credentials or game-parity claims. Reply using the supplied strict JSON schema only.',
        'sections': [('tools/PS2Recomp/ps2xIOP/src/emulator/iop_emulator.cpp', 425, 575),
                     ('tools/PS2Recomp/ps2xIOP/src/emulator/iop_emulator.cpp', 635, 755),
                     ('tools/PS2Recomp/ps2xIOP/src/emulator/iop_emulator.cpp', 985, 1055)],
    },
    'signed-width-oracle': {
        'objective': 'Independently review regression cases for signed low64 branch predicates in the excerpts. For values 0x0000000080000000, 0x0000000100000000, 0xffffffff00000000, 0x8000000000000000 and zero, derive which of <0, >=0, <=0 and >0 are true using signed64, and identify cases that signed32 would misclassify. Recommend delay-slot tests for taken/not-taken likely and ordinary branches. At most six findings. This is a mathematical test review, not proof of R5900 hardware parity. Do not browse, run code, access files or request credentials.',
        'sections': [('tools/PS2Recomp/ps2xRecomp/src/lib/control_flow_emitter.cpp', 398, 435),
                     ('tools/PS2Recomp/ps2xRecomp/src/lib/control_flow_emitter.cpp', 455, 495)],
    },
    'native-presentation': {
        'objective': 'Review the smallest native integration of the actual EE scheduler with the existing GS presented-frame path and input. Identify exact calls and lifecycle risks, propose meaningful integration tests. Use only these excerpts. No fabricated title frame, source edit or build. Findings are advice, not parity evidence.',
        'sections': [('src/native_presenter.cpp', 1, 160),
                     ('src/main.cpp', 265, 300),
                     ('tools/PS2Recomp/ps2xRuntime/src/lib/Kernel/EeScheduler.cpp', 157, 170),
                     ('tools/PS2Recomp/ps2xRuntime/src/lib/Kernel/EeScheduler.cpp', 1890, 1945),
                     ('tests/integration/native_presenter_contract.cpp', 1, 85)],
    },
    'signed-branch-emitter': {
        'objective': 'Review signed R5900 branch emission, low64 width, link semantics and likely delay-slot annulment. Identify a concrete remaining defect or state the uncertainty. Propose a focused regression test using values whose signed32 and signed64 predicates differ. Review only, no edits/builds. Existing generated corpus is not regenerated by these edits.',
        'sections': [('tools/PS2Recomp/ps2xRecomp/src/lib/control_flow_emitter.cpp', 1, 230),
                     ('tools/PS2Recomp/ps2xRecomp/src/lib/control_flow_emitter.cpp', 230, 490)],
    },
}


def sha(raw):
    return hashlib.sha256(raw).hexdigest()


def canonical(value):
    return json.dumps(value, sort_keys=True, separators=(',', ':'), ensure_ascii=True,
                      allow_nan=False).encode('utf-8')


def unique_pairs(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError('Duplicate JSON key')
        result[key] = value
    return result


def read_bounded(path):
    with path.open('rb') as stream:
        raw = stream.read(MAX_JSON + 1)
    if len(raw) > MAX_JSON:
        raise ValueError('JSON exceeds bounded size')
    return raw


def read_json(path):
    raw = read_bounded(path)
    def bad_constant(value):
        raise ValueError('Nonfinite JSON number')
    return json.loads(raw.decode('utf-8-sig'), object_pairs_hook=unique_pairs,
                      parse_constant=bad_constant)


def write_new(path, value):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open('xb') as stream:
        stream.write(json.dumps(value, ensure_ascii=False, indent=2, allow_nan=False).encode('utf-8'))


def source_path(root, name):
    path = root / name
    if Path(name).is_absolute() or '..' in Path(name).parts or not path.resolve().is_relative_to(root.resolve()):
        raise ValueError('Source outside workspace')
    if path.is_symlink() or path.is_junction():
        raise ValueError('Linked source')
    return path


def enqueue(kind, bridge=DEFAULT, root=ROOT):
    task = TASKS[kind]
    sources = {}
    sections = []
    for name, start, stop in task['sections']:
        raw = source_path(root, name).read_bytes()
        if len(raw) > 1024 * 1024:
            raise ValueError('Source too large for bounded review')
        lines = raw.decode('utf-8-sig').splitlines()
        stop = min(stop, len(lines))
        if not 1 <= start <= stop:
            raise ValueError('Invalid source excerpt')
        prior = sources.get(name)
        identity = {'sha256': sha(raw), 'lines': len(lines)}
        if prior is not None and prior != identity:
            raise ValueError('Source changed during export')
        sources[name] = identity
        sections.append({'path': name, 'start': start, 'end': stop,
                         'text': '\n'.join(f'{n}: {lines[n-1]}' for n in range(start, stop+1))})
    payload = {'schema_version': 1, 'kind': kind, 'objective': task['objective'],
               'sources': sources, 'excerpts': sections, 'max_findings': 6}
    checksum = sha(canonical(payload))
    identifier = kind + '-' + checksum[:24]
    path = bridge / 'requests' / (identifier + '.json')
    envelope = {'request_id': identifier, 'request_sha256': checksum, 'payload': payload}
    if len(canonical(envelope)) > MAX_JSON:
        raise ValueError('Request exceeds bounded size')
    if path.exists():
        if read_json(path) != envelope:
            raise ValueError('Existing request changed')
    else:
        write_new(path, envelope)
    (bridge / 'replies').mkdir(parents=True, exist_ok=True)
    refresh(bridge, root)
    return identifier


def verify_request(value):
    if type(value) is not dict or set(value) != {'request_id', 'request_sha256', 'payload'}:
        raise ValueError('Invalid request envelope')
    checksum = sha(canonical(value['payload']))
    expected = value['payload']['kind'] + '-' + checksum[:24]
    if value['request_sha256'] != checksum or value['request_id'] != expected:
        raise ValueError('Request integrity mismatch')


def bounded_text(value, limit):
    return isinstance(value, str) and 0 < len(value) <= limit


def check_sources(request, root):
    """Recheck live inputs even when this reply has been collected before."""
    current = {}
    for name, identity in request['payload']['sources'].items():
        try:
            observed = sha(source_path(root, name).read_bytes())
            current[name] = {'sha256': observed,
                             'state': 'MATCH' if observed == identity['sha256'] else 'CHANGED'}
        except (OSError, ValueError) as error:
            current[name] = {'state': 'UNAVAILABLE', 'error_type': type(error).__name__}
    return current


def validate_reply(reply, request):
    verify_request(request)
    if type(reply) is not dict or set(reply) != {'request_id', 'request_sha256', 'findings'}:
        raise ValueError('Invalid reply fields')
    if any(reply[key] != request[key] for key in ('request_id', 'request_sha256')):
        raise ValueError('Reply references a different request')
    findings = reply['findings']
    if type(findings) is not list or len(findings) > request['payload']['max_findings']:
        raise ValueError('Invalid finding count')
    keys = {'title', 'path', 'line', 'evidence', 'recommendation', 'test'}
    for item in findings:
        if type(item) is not dict or set(item) != keys:
            raise ValueError('Invalid finding fields')
        if any(not bounded_text(item[key], 3000) for key in ('title', 'evidence', 'recommendation', 'test')):
            raise ValueError('Invalid finding text')
        if type(item['path']) is not str or item['path'] not in request['payload']['sources']:
            raise ValueError('Unknown source reference')
        if type(item['line']) is not int or not any(
            section['path'] == item['path'] and section['start'] <= item['line'] <= section['end']
            for section in request['payload']['excerpts']):
            raise ValueError('Reference outside reviewed excerpt')


def collect(bridge=DEFAULT, root=ROOT):
    receipts = []
    for path in sorted((bridge / 'replies').glob('*.json')):
        identifier = path.stem
        if not re.fullmatch(r'[a-z-]+-[0-9a-f]{24}', identifier):
            continue
        request_path = bridge / 'requests' / path.name
        if not request_path.is_file():
            continue
        raw = read_bounded(path)
        reply_hash = sha(raw)
        current = {}
        state, reason = 'COLLECTED_UNREVIEWED', 'Schema and input hashes match; semantic review is still required.'
        try:
            request = read_json(request_path)
            validate_reply(read_json(path), request)
            current = check_sources(request, root)
            if any(item['state'] != 'MATCH' for item in current.values()):
                state, reason = 'STALE_SOURCE', 'Source changed or is unavailable; do not accept as a current review.'
        except (ValueError, KeyError, OSError, TypeError) as error:
            state, reason = 'REJECTED', type(error).__name__
        receipt = {'request_id': identifier, 'reply_sha256': reply_hash, 'state': state,
                   'reason': reason, 'source_validation': current,
                   'code_applied': False, 'parity_verified': False}
        # Append a new observation if live inputs changed. Older receipts remain
        # historical evidence; they must not authorize advice for newer sources.
        revision = sha(canonical(receipt))[:24]
        receipt_path = bridge / 'receipts' / f'{identifier}-{reply_hash}-{revision}.json'
        # Preserve exact worker output without interpreting or executing it.
        raw_path = bridge / 'raw' / f'{identifier}-{reply_hash}.json'
        raw_path.parent.mkdir(parents=True, exist_ok=True)
        if raw_path.exists():
            if read_bounded(raw_path) != raw:
                raise ValueError('Preserved reply integrity mismatch')
        else:
            with raw_path.open('xb') as stream:
                stream.write(raw)
        if receipt_path.exists():
            if read_json(receipt_path) != receipt:
                raise ValueError('Preserved receipt integrity mismatch')
        else:
            write_new(receipt_path, receipt)
        receipts.append(receipt)
    refresh(bridge, root)
    return receipts


def refresh(bridge=DEFAULT, root=ROOT):
    items = []
    for path in sorted((bridge / 'requests').glob('*.json')):
        request = read_json(path)
        verify_request(request)
        reply = bridge / 'replies' / path.name
        submitted = (bridge / 'submissions' / path.name).exists()
        current = check_sources(request, root)
        stale = any(item['state'] != 'MATCH' for item in current.values())
        items.append({'request_id': request['request_id'], 'request_sha256': request['request_sha256'],
                      'request_file': str(path.resolve()), 'reply_file': str(reply.resolve()),
                      'source_validation': current,
                      'state': 'REPLY_PRESENT' if reply.exists() else 'SUBMITTED_OR_UNCERTAIN' if submitted
                               else 'STALE_SOURCE' if stale else 'READY'})
    value = {'schema_version': 1, 'max_jobs_per_run': 1, 'requests': items,
             'reply_schema': {'request_id': 'exact request_id', 'request_sha256': 'exact request_sha256',
                 'findings': [{'title': 'short finding', 'path': 'source path from request',
                              'line': 1, 'evidence': 'observed source behavior or explicit uncertainty',
                              'recommendation': 'proposed change, not applied code',
                              'test': 'concrete behavioral test'}]},
             'semantic_review_required': True, 'code_execution_from_replies': False}
    bridge.mkdir(parents=True, exist_ok=True)
    temporary = bridge / 'inbox.new.json'
    temporary.write_text(json.dumps(value, indent=2), encoding='utf-8')
    temporary.replace(bridge / 'inbox.json')
    return value


def reserve_ui(identifier, bridge=DEFAULT, root=ROOT):
    if not re.fullmatch(r'[a-z-]+-[0-9a-f]{24}', identifier):
        raise ValueError('Invalid request ID')
    request = read_json(bridge / 'requests' / (identifier + '.json'))
    verify_request(request)
    if (bridge / 'replies' / (identifier + '.json')).exists():
        raise ValueError('Request already has a reply')
    if any(item['state'] != 'MATCH' for item in check_sources(request, root).values()):
        raise ValueError('Request sources changed or are unavailable')
    write_new(bridge / 'submissions' / (identifier + '.json'), {
        'request_id': identifier, 'request_sha256': request['request_sha256'],
        'state': 'SUBMITTED_OR_UNCERTAIN', 'transport': 'computer-use',
        'automatic_retry': False})
    refresh(bridge, root)
    return request


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('command', choices=('enqueue', 'collect', 'status', 'reserve-ui'))
    parser.add_argument('--kind', choices=tuple(TASKS))
    parser.add_argument('--request-id')
    parser.add_argument('--bridge', type=Path, default=DEFAULT)
    args = parser.parse_args()
    if args.command == 'enqueue':
        if not args.kind:
            parser.error('enqueue requires --kind')
        value = enqueue(args.kind, args.bridge)
    elif args.command == 'collect':
        value = collect(args.bridge)
    elif args.command == 'reserve-ui':
        if not args.request_id:
            parser.error('reserve-ui requires --request-id')
        value = reserve_ui(args.request_id, args.bridge)
    else:
        value = refresh(args.bridge)
    print(json.dumps(value, indent=2))


if __name__ == '__main__':
    main()
