"""Extract a reviewed continuation from preserved translation, bound to ELF words.

Produces a candidate include and provenance; never edits the dispatcher or runs
model output. The caller must review the candidate and run behavioral contracts.
"""
import argparse
import hashlib
import json
import re
from pathlib import Path

from generate_resume_catalog import elf_words, without_cpp_comments


def recover(source, words, start, stop):
    if start % 4 or stop % 4 or not start < stop or stop - start > 16384:
        raise ValueError('Invalid bounded instruction range')
    labels = list(re.finditer(r'^label_([0-9a-fA-F]+):\s*$', source, re.M))
    positions = {int(m[1], 16): m.start() for m in labels}
    if start not in positions or stop not in positions:
        raise ValueError('Range requires exact source boundary labels')
    body = source[positions[start]:positions[stop]]
    annotations = [(int(a,16),int(w,16)) for a,w in
                   re.findall(r'//\s*0x([0-9a-fA-F]+):\s*0x([0-9a-fA-F]+)\s', body)]
    expected = set(range(start, stop, 4))
    if set(a for a,_ in annotations) != expected:
        raise ValueError('Continuation has missing or out-of-range annotations')
    if any(words.get(a) != w for a,w in annotations):
        raise ValueError('Source annotation differs from original ELF')
    # A delay-only resume may fall through the requested boundary. Preserve
    # its already assigned PC and hand control back to the guest scheduler.
    boundary = (r'(ctx->pc\s*=\s*0x0*' + f'{stop:x}' +
                r'u;\s*)goto\s+label_0*' + f'{stop:x}' + r';')
    body = re.sub(boundary, r'\1return;', body, flags=re.I)
    code = without_cpp_comments(body)
    defined = set(re.findall(r'^(label_[0-9a-fA-F]+):', code, re.M))
    targets = set(re.findall(r'goto\s+(label_[0-9a-fA-F]+)\s*;', code))
    if targets - defined:
        raise ValueError('Continuation jumps outside extracted labels')
    if code.count('{') != code.count('}'):
        raise ValueError('Range cuts through a structured code block')

    # R5900 signed integer branches inspect the signed low 64-bit lane.
    # Accept only the known emitter expression with matching original opcode,
    # register and comparison; do not rewrite arbitrary source expressions.
    corrections = []
    pattern = (r'(const bool branch_taken_0x([0-9a-fA-F]+) = \()'
               r'GPR_S32\(ctx, (\d+)\) (<=|>=|<|>) 0(\);)')
    def repair(m):
        pc, register = int(m[2],16), int(m[3])
        w = words.get(pc, 0)
        op, rs, rt = w >> 26, w >> 21 & 31, w >> 16 & 31
        comparison = {6:'<=',22:'<=',7:'>',23:'>'}.get(op)
        if op == 1:
            comparison = '<' if rt in (0,2,16,18) else '>=' if rt in (1,3,17,19) else None
        if pc not in expected or rs != register or comparison != m[4]:
            raise ValueError('Signed branch expression does not match original instruction')
        corrections.append({'pc':f'0x{pc:08x}','from':'GPR_S32','to':'GPR_S64'})
        return m[1] + f'GPR_S64(ctx, {register}) {comparison} 0' + m[5]
    body = re.sub(pattern, repair, body)
    if re.search(r'branch_taken[^\n]*GPR_S32', body):
        raise ValueError('Unsupported signed branch expression requires review')
    symbol = f'fate_recovered_{start:08x}'
    pcs = sorted(int(x[6:],16) for x in defined)
    if set(pcs) != expected:
        raise ValueError('Every original instruction requires an exact entry label')
    output = [
        '// Generated by tools/recover_continuation.py; reviewed candidate, not parity proof.',
        '#pragma warning(push)', '#pragma warning(disable: 4702)',
        f'constexpr std::array<uint32_t,{len(expected)}> {symbol}_words{{',
        ','.join(f'0x{words[pc]:08x}u' for pc in range(start,stop,4)), '};',
        f'void {symbol}(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {{',
        '    switch(ctx->pc) {']
    output.extend(f'    case 0x{pc:08x}u: goto label_{pc:x};' for pc in pcs)
    output += ['    default: throw std::runtime_error("Unexpected recovered continuation PC");',
               '    }',body,'}','#pragma warning(pop)','']
    return '\n'.join(output), corrections


def main():
    p=argparse.ArgumentParser(description=__doc__)
    for name in ('elf','source','output','report'): p.add_argument('--'+name,type=Path,required=True)
    for name in ('start','stop'): p.add_argument('--'+name,type=lambda s:int(s,0),required=True)
    a=p.parse_args(); blob=a.elf.read_bytes(); raw=a.source.read_bytes()
    result,corrections=recover(raw.decode('utf-8-sig'),elf_words(blob),a.start,a.stop)
    if a.output.exists() or a.report.exists(): raise ValueError('Candidate outputs must be new')
    a.output.parent.mkdir(parents=True,exist_ok=True)
    a.output.write_text(result,encoding='utf-8',newline='\n')
    evidence={'elf_sha256':hashlib.sha256(blob).hexdigest(),'source_sha256':hashlib.sha256(raw).hexdigest(),
              'candidate_sha256':hashlib.sha256(a.output.read_bytes()).hexdigest(),
              'start':a.start,'stop_exclusive':a.stop,'instructions':(a.stop-a.start)//4,
              'signed_branch_corrections':corrections,'semantic_status':'REQUIRES_REVIEW_AND_CONTRACTS'}
    a.report.write_text(json.dumps(evidence,indent=2)+'\n',encoding='utf-8')
    print(json.dumps(evidence))


if __name__=='__main__': main()
