# Prefer an installed SDL2 package, including scripts/build_native.ps1 output.
find_package(SDL2 CONFIG QUIET NO_MODULE)
if(TARGET SDL2::SDL2)
    set(SDL2_FOUND TRUE)
    return()
endif()
find_path(SDL2_INCLUDE_DIR NAMES SDL.h PATH_SUFFIXES SDL2)
find_library(SDL2_LIBRARY NAMES SDL2)
find_library(SDL2MAIN_LIBRARY NAMES SDL2main)
find_file(SDL2_DLL NAMES SDL2.dll PATH_SUFFIXES bin)
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(SDL2 REQUIRED_VARS SDL2_LIBRARY SDL2_INCLUDE_DIR)
if(SDL2_FOUND AND NOT TARGET SDL2::SDL2)
    if(SDL2_DLL)
        add_library(SDL2::SDL2 SHARED IMPORTED)
        set_target_properties(SDL2::SDL2 PROPERTIES
            IMPORTED_IMPLIB "${SDL2_LIBRARY}" IMPORTED_LOCATION "${SDL2_DLL}")
    else()
        add_library(SDL2::SDL2 UNKNOWN IMPORTED)
        set_target_properties(SDL2::SDL2 PROPERTIES IMPORTED_LOCATION "${SDL2_LIBRARY}")
    endif()
    set_target_properties(SDL2::SDL2 PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${SDL2_INCLUDE_DIR}")
    if(SDL2MAIN_LIBRARY)
        add_library(SDL2::SDL2main STATIC IMPORTED)
        set_target_properties(SDL2::SDL2main PROPERTIES IMPORTED_LOCATION "${SDL2MAIN_LIBRARY}")
    endif()
endif()
